spring:
  application:
    name: ead-api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: "${ead-config-server-username}"
      password: "${ead-config-server-password}"